language: node_js
env:
- NODE_ENV=test
node_js:
- '8'
script:
- yarn run lint
deploy:
  provider: npm
  email: wojciech.g.krysiak@gmail.com
  api_key:
    secure: ErvHcJqXRxiO0P/nQccYl68YpiK7OWx4BlakZ/4+LofXPz4V2Mr8JrEyrbzz96pa+fByNKsOhu0VUesgc8g/NVWqPqzMYu2KstNVxMorpJ485WyF/hthqbavVTDcaR7xwrpCmJAIB/FriY16oni1wNEcDIDfIMRdIpYaHYnrc/xqWEYS49DRVSWdJ2v18EzDAvQfkda3eMgbC/u7LiVvY9tzjJ0kw1RipoI/+9WrPbtjfKTaBAU+KfoekdrO7CHsg26lxoHOcqMXvp+Z0XhmvdfilM+/45HZK16aqajTtRgaeu+O6ZO243B3DUPJQ8pV31ZJcIIxrE4qliLgdMLJbOFhdBSGbSRlHR04LNb2HOsFG0s6LgDK7zyefQyWN6xtu5DaHH4r94cf9HvMwT+qPTbYZGhEKQVfusQWxUN2RIUu3rJCaYjpGW6NhNcTiILrM4TqVLXslrTM3HPq/l3V0LcHH/Vrvl+NFK2Bvr/DubJ6LNU96O6gE3b9wa7eq5CdgwN9h4SB/RFK1Lh5Owuu7o2AW7cjcm+ZhGQjpvhVHf9UdUPmm1qxIwyqDWkxUj/DloOMoP6WR8zia6jNeVJDOI+leGm2TxJGyxl2QPtH4tBgEadxf5yOU9DK76hBfKPPmweEPv7kezh6xl5ffV7I/E3OQbEKkwZ7544G+Cq4DBk=
  on:
    tags: true
    repo: SoftwareBrothers/admin-bro-hapijs
